### ISSUE TITLE
Enable internal search

### ISSUE THREAD

**Issue by ThorstenHans** [spinkube/documentation#1]
Set up a gcs_engine_id at https://programmablesearchengine.google.com/controlpanel/create

Add that gcs_engine_id to the SpinKube/documentation/hugo.toml file:

```toml
[params]
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "TODO"
```
