### ISSUE TITLE
Set up "Feedback"

### ISSUE THREAD

**Issue by tpmccallum** [spinkube/documentation#118]
Each page in the documentation has a "Feedback" section where the user can click "Yes" or "No" (in response to the question, "Was this page helpful?").

![Screenshot 2024-03-14 at 20 45 03](https://github.com/spinkube/documentation/assets/9831342/e9941335-c4e6-4f3b-9010-e1a5f9dc7bab)

The result of a user's clicking "Yes" or "No" is configurable[1].
The feedback can also be accessed [2] to improve the website's pages.

Can the Google Analytics (GA4) events [3] be configured to provide access to helpful data about user engagement?

[1] https://www.docsy.dev/docs/adding-content/feedback/#setup-1
[2] https://www.docsy.dev/docs/adding-content/feedback/#access-the-feedback-data
[3] https://support.google.com/analytics/answer/9322688#

**Comment by tpmccallum** [comment]
Unfortunately it is not possible to trigger Plausible events via Docsy. Plausible requires a special class attribute e.g. `FeedBack+Yes` in the `button` element. This will require upstream changes. 
At present the configuration for the `button` elements are done as text in the site's `hugo.toml` file:
```toml
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/spinkube/documentation/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/spinkube/documentation/issues/new">tell us how we can improve</a>.'
```
